easy_admin:
    site_name: 'YOUPI INTRANET'
    design:
        brand_color: '#200157'
    entities:
        # List the entity class name you want to manage
        - App\Entity\User
        - App\Entity\Subject
        - App\Entity\Grades
