<?php

namespace App\Repository;

/**
 * GradesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradesRepository extends \Doctrine\ORM\EntityRepository
{
}
